apiVersion: v1
kind: Service
metadata:
  name: helm-scan-service
spec:
  selector:
    app: helm-scan
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080 