name: Test-and-Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: e2e and unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Install Ginkgo
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo@latest

    - name: Download dependencies
      run: go mod download

    - name: Run Unit Tests
      run: go test -race -coverprofile=unit-coverage.txt -covermode=atomic $(go list ./... | grep -v "e2e")

    - name: Run the application
      run: |
        nohup go run ./cmd/helm-scan/main.go > server.log 2>&1 &
        # Wait for the server to start
        sleep 30
        # Check server logs in case of startup issues
        cat server.log

        ginkgo ./e2e

    - name: Generate Combined Coverage
      run: |
        go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        flags: unittests,e2etests